### ISSUE TITLE
reimplement packager functions parent issue

### ISSUE THREAD

**Issue by schristoff** [zarf-dev/zarf#2969]
**Purpose:**
As part of schema work it has been identified that `src/packager` intertwines "deploy time" and "package create time" logic. This makes it burdensome, or possibly impossible, to implement versioned schemas without passing a versioned structs throughout the codebase. 

We will begin by refactoring the following pieces of `src/packager` into `src/packager2` - this will allow us to re-implement this functionality without making breaking changes to Zarf in between releases. We will then swap over the calls to `packager.()` functions to `packager2.()` and deprecate `src/packager` functionality for `src/packager2` (while renaming packager2 to packager)

**Decisions Made:**
- To refactor "Opts" out of the larger Packager struct, `Opts` will be moved into their respective "primary file". All exported functions will take its "related" `Opts` struct as a function argument. 
E.g. - [InspectOpts](https://github.com/zarf-dev/zarf/blob/cf4e9891d531b792849394f80830363411242fd9/src/types/packager.go#L27) is moved into the [inspect.go](https://github.com/zarf-dev/zarf/pull/2990/files#diff-ce1d4a01e228f255d9bda4038e0ba0c7dc1d8f798d3629503d4e137076e6f90aR14) file within `packager2`

**To Be Worked:** 
- [x] [func New(cfg *types.PackagerConfig, mods ...Modifier) (*Packager, error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#New)
- [x] [func (p *Packager) ClearTempPaths()](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.ClearTempPaths)
- [x] [func (p *Packager) Create(ctx context.Context) error](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Create)
- [ ] [func (p *Packager) Deploy(ctx context.Context) error](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Deploy)
- [ ] [func (p *Packager) DevDeploy(ctx context.Context) error](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.DevDeploy)
- [ ] [func (p *Packager) FindImages(ctx context.Context) (map[string][]string, error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.FindImages)
- [ ] [func (p *Packager) Generate() (err error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Generate)
- [ ] [func (p *Packager) GetVariableConfig() *variables.VariableConfig](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.GetVariableConfig)
- [x] [func (p *Packager) Inspect(ctx context.Context) (err error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Inspect)
- [x] [func (p *Packager) Lint(ctx context.Context) error](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Lint)
- [x] [func (p *Packager) Mirror(ctx context.Context) error](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Mirror)
- [ ] [func (p *Packager) Publish(ctx context.Context) (err error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Publish)
- [x] [func (p *Packager) Pull(ctx context.Context) (err error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Pull)
- [x] [func (p *Packager) Remove(ctx context.Context) (err error)](https://pkg.go.dev/github.com/defenseunicorns/zarf/src/pkg/packager#Packager.Remove)
