### ISSUE TITLE
Additional Terratest E2E tests

### ISSUE THREAD

**Issue by RothAndrew** [zarf-dev/zarf#99]
Now that the framework is in place for ephemeral E2E tests we should add more, with the goal being the eventual elimination of the GitLab-based E2E testing using the `e2e.sh` shell script.

- Let's start making the GitHub Actions based tests required in PRs through the Branch Protection Rule in the repo settings
- E2E tests should all run in parallel to minimize the time it takes to run them
- There's a ton of setup/boilerplate code in the existing Terratest-based E2E test. We should be as DRY as we can and reuse stuff that will be the same for different tests
- Along with whatever is in `e2e.sh`, deploying a few of the examples would be great candidates for new E2E tests

Tests that are needed:

- [x] tests basic functionality of Gitea and Grafana (#234, #238)
- [x] #243
- [ ] tests a data injection package (#242)
- [ ] tests a git-based helm chart (#242)

**Comment by RothAndrew** [comment]
We really need an terratest-based E2E test that uses gitops
